### PR TITLE
Add bootstrap and remove app-network from compose file.

### PR DESCRIPTION
**Pull request by marcusmyers**
In order to setup the project for development, this commit adds a
`script/bootstrap` file to install dependencies and add an `.env` file
to use with docker setup.  This commit also removes the `app-network`
from the `docker-compose.yml` file as `docker-compose` creates a default
network that is bridged by default.  To verify run `docker network ls`
after you have run `script/bootstrap`.  This commit fixes issue #4.

### CODE REVIEW

**Comment by xdega** [comment]
This looks like a good addition. My only concern with this is for Windows users. Would it be possible to create a batch file equivalent of the bootstrap script before the merge?

I would like to try and support platforms equally, if possible, taking full advantage of the fact that Docker is cross-platform.

**Comment by m1guelpf** [comment]
Could this be also submitted to the other branch?

**Comment by marcusmyers** [comment]
@m1guelpf Which branch is that?

**Comment by xdega** [comment]
@marcusmyers I believe he is referring to the `upgrade-only` branch.

**Comment by marcusmyers** [comment]
@xdega Amended in 7d6fe42 with a powershell script for bootstrap on Windows machines.

**Comment by marcusmyers** [comment]
@m1guelpf Pull request created [here](https://github.com/xdega/laravel-with-docker/pull/8).

**Comment by xdega** [comment]
@marcusmyers Awesome work. Be sure to submit a PR. Merging this in. Be sure to update the `README.md`

**Pull request merged**
